version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=pos_db
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    # ADD THIS HEALTHCHECK SECTION
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d pos_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    restart: on-failure # This is a better setting
    ports:
      - '3001:3001'
    # UPDATE THE depends_on SECTION
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://myuser:mypassword@db:5432/pos_db

  frontend:
    build: ./frontend
    restart: always
    ports:
      - '3000:5173'
    depends_on:
      - backend

volumes:
  db_data: